version: '3'
services:
  app:
    build: .
    environment:
      - SCRIPT_ON_RUN="/example-script-on-run.sh"
      - POSTGRES_USER="usuario_ladm_col"
      - POSTGRES_PASS="clave_ladm_col"
      - POSTGRES_DBNAME="ladm_col"
    ports:
      - "8000:8000"
      - "5432:5432"
    volumes:
      - ./src:/var/www/html
      - ./scripts:/scripts
