version: '3'
services:
  app:
    build: .
    privileged: true # obligatory for centos systemd!
    environment:
      - SCRIPT_ON_RUN="/scripts/example-script-on-run.sh" # optional
      #- DATABASE_HOST="localhost"
      - DATABASE_PORT=5433
      - DATABASE_NAME=db_test
      - DATABASE_USER=user_db
      - DATABASE_PASSWORD=abc123
      - WEBSERVER_PATH=/htdocs/ # use ending "/" mandatory
      - WEBSERVER_PORT=82
      - VARNISH_PORT=81
    ports:
      - 81:81
      - 82:82
      - 5431:5431
    volumes:
      # obligatory for centos systemd https://github.com/solita/docker-systemd/issues/1
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
      # specific
      - ./scripts:/scripts:ro
      - ./htdocs:/htdocs
